linters:
  enable:
  - bodyclose
  - dupl
  - exportloopref
  - gochecknoinits
  - gocritic
  - gofmt
  - gofumpt
  - lll
  - misspell
  - nilerr
  - prealloc
  - revive
  - unconvert
  - wastedassign
  - whitespace

issues:
  exclude-use-default: false

linters-settings:
  errcheck:
    exclude-functions:
    - io.Copy
    - (io.Closer).Close
    - (io.Writer).Write
    - (hash.Hash).Write
    - (net.Conn).Close
    - (net.Conn).SetReadDeadline
    - (net.Conn).SetWriteDeadline
    - (*net.TCPConn).SetKeepAlive
    - (*net.TCPConn).SetKeepAlivePeriod
    - (*net.TCPConn).SetNoDelay
    - (*net.UDPConn).Close
    - (net.Listener).Close
    - (net.PacketConn).Close
    - (net.PacketConn).SetReadDeadline
    - (net.PacketConn).SetWriteDeadline
    - (net/http.ResponseWriter).Write
    - (*net/http.Server).Serve
    - (*net/http.Server).ServeTLS
    - (*net/http.Server).Shutdown
    - os.Chdir
    - os.Mkdir
    - os.MkdirAll
    - os.Remove
    - os.RemoveAll
    - os.Setenv
    - os.Unsetenv
    - (*os.File).WriteString
    - (*os.File).Close
    - (github.com/datarhei/gosrt.Conn).Close
    - (github.com/datarhei/gosrt.Conn).SetReadDeadline
    - (github.com/datarhei/gosrt.Conn).SetWriteDeadline

  govet:
    enable-all: true
    disable:
    - fieldalignment
    - reflectvaluecompare
    - shadow
