linters:
  enable:
  - bodyclose
  - dupl
  - exportloopref
  - gochecknoinits
  - gocritic
  - gofmt
  - gofumpt
  - lll
  - misspell
  - nilerr
  - prealloc
  - revive
  - unconvert
  - wastedassign
  - whitespace
  disable:
  - errcheck

issues:
  exclude-use-default: false

linters-settings:
  govet:
    enable-all: true
    disable:
    - fieldalignment
    - reflectvaluecompare
    - shadow
